export const POPULAR_VIDEOS_REQUEST = "POPULAR_VIDEOS_REQUEST";
export const POPULAR_VIDEOS_SUCCESS = "POPULAR_VIDEOS_SUCCESS";
export const POPULAR_VIDEOS_FAIL = "POPULAR_VIDEOS_FAIL";

export const VIDEO_DATA_REQUEST = "VIDEO_DATA_REQUEST";
export const VIDEO_DATA_SUCCESS = "VIDEO_DATA_SUCCESS";
export const VIDEO_DATA_FAIL = "VIDEO_DATA_FAIL";

export const METAD_REQUEST = "METAD_REQUEST";
export const METAD_SUCCESS = "METAD_SUCCESS";
export const METAD_FAIL = "METAD_FAIL";

export const CHANNEL_DATA_REQUEST = "CHANNEL_DATA_REQUEST";
export const CHANNEL_DATA_SUCCESS = "CHANNEL_DATA_SUCCESS";
export const CHANNEL_DATA_FAIL = "CHANNEL_DATA_FAIL";

export const RELATED_VIDEOS_REQUEST = "RELATED_VIDEOS_REQUEST";
export const RELATED_VIDEOS_SUCCESS = "RELATED_VIDEOS_SUCCESS";
export const RELATED_VIDEOS_FAIL = "RELATED_VIDEOS_FAIL";

export const COMMENTS_REQUEST = "COMMENTS_REQUEST";
export const COMMENTS_SUCCESS = "COMMENTS_SUCCESS";
export const COMMENTS_FAIL = "COMMENTS_FAIL";

export const CHANNEL_VIDEOS_REQUEST = "CHANNEL_VIDEOS_REQUEST";
export const CHANNEL_VIDEOS_SUCCESS = "CHANNEL_VIDEOS_SUCCESS";
export const CHANNEL_VIDEOS_FAIL = "CHANNEL_VIDEOS_FAIL";

export const SEARCHED_VIDEOS_REQUEST = "SEARCHED_VIDEOS_REQUEST";
export const SEARCHED_VIDEOS_SUCCESS = "SEARCHED_VIDEOS_SUCCESS";
export const SEARCHED_VIDEOS_FAIL = "SEARCHED_VIDEOS_FAIL";

export const LBRY_SEARCH_REQUEST = "LBRY_SEARCH_REQUEST";
export const LBRY_SEARCH_SUCCESS = "LBRY_SEARCH_SUCCESS";
export const LBRY_SEARCH_FAIL = "LBRY_SEARCH_FAIL";

export const YOUTUBE_SEARCH_REQUEST = "YOUTUBE_SEARCH_REQUEST";
export const YOUTUBE_SEARCH_SUCCESS = "YOUTUBE_SEARCH_SUCCESS";
export const YOUTUBE_SEARCH_FAIL = "YOUTUBE_SEARCH_FAIL";

export const POPCORN_SEARCH_REQUEST = "POPCORN_SEARCH_REQUEST";
export const POPCORN_SEARCH_SUCCESS = "POPCORN_SEARCH_SUCCESS";
export const POPCORN_SEARCH_FAIL = "POPCORN_SEARCH_FAIL";
